### ISSUE TITLE
Missing dataset and checkpoints

### ISSUE THREAD

**Issue by engr3os** [asheshjain399/RNNexp#1]
Hi,

Can you please provide the dataset and checkpoint for the RNN implemetation?

I can't find the dataset folders in the repo. I need to correct the following lines in maneuver-rnn.py

path_to_dataset = '/scr/ashesh/brain4cars/dataset/{0}'.format(fold)
path_to_checkpoints = '/scr/ashesh/brain4cars/checkpoints/{0}'.format(fold)

Thanks.

**Comment by asheshjain399** [comment]
Definitely !!

I'll update this soon. Give me few days.

**Comment by asheshjain399** [comment]
Checkpoints and data set is now also available in the checkpoints/ directory.
