### ISSUE TITLE
S-RNN, ERD, and LSTM-3LR pretrained models

### ISSUE THREAD

**Issue by una-dinosauria** [asheshjain399/RNNexp#5]
Sorry, where can I download the pretrained models for S-RNN, ERD, and LSTM-3LR? The [readme](https://github.com/asheshjain399/RNNexp/blob/srnn/structural_rnn/README.md) has a self-referencing link to https://github.com/asheshjain399/RNNexp/blob/srnn/structural_rnn

**Comment by asheshjain399** [comment]
Pre-trained models are too big to be hosted on github. I'll soon post the their url for download.

**Comment by una-dinosauria** [comment]
Thanks!

**Comment by una-dinosauria** [comment]
Hi again, sorry, have the models been uploaded?

**Comment by asheshjain399** [comment]
Trained models are available here: https://drive.google.com/open?id=0B7lfjqylzqmMZlI3TUNUUEFQMXc

I will update the Readme with this url.
