### ISSUE TITLE
Pretrained models notavailable

### ISSUE THREAD

**Issue by ParthaEth** [asheshjain399/RNNexp#8]
Hi,

I am trying to download pre-trained SRNN and 3LR models as instructed in there "Pre-trained models of S-RNN, ERD, and LSTM-3LR can be downloaded from here" (readme file) but I can not download the models. Clicking on the links brings me back on the same page and no download starts. It would be great if you could have a look at it.

**Comment by asheshjain399** [comment]
My bad, I copied the wrong url. Here is the correct URL https://drive.google.com/open?id=0B7lfjqylzqmMZlI3TUNUUEFQMXc
